version: "3"

services:
    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: trainwarehouse
        ports:
            - 3306:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 9090:8080
